FROM alpine:3

LABEL author="Rifaldi Noviansyah"
LABEL company="Learn Docker" linkedin="https://www.linkedin.com/in/rifaldi-noviansyah-a477151b8/"

RUN mkdir hello
RUN echo "hello world" > "hello/world.txt"

CMD cat "hello/world.txt"